### ISSUE TITLE
Documentation for this project

### ISSUE THREAD

**Issue by EightBitBoy** [netresearch/dhl-shipping-m2#1]
Since https://github.com/netresearch/dhl-module-shipping-m2 is deprecated and the new module https://github.com/netresearch/dhl-shipping-m2 should be used I wonder if there is any documentation for this project, both technical documentation and some guidance for shop owners.

Can you provide those resources?

**Comment by mam08ixo** [comment]
Please use the vendor FAQ as a starting point: [Where can I find the documentation for the DHL Shipping extension?|https://dhl.support.netresearch.de/support/solutions/articles/12000023174-where-can-i-find-the-documentation-for-the-versenden-shipping-extension-]

The Wiki for this repository will be published with the next extension version release.
