### ISSUE TITLE
DHL module config issue

### ISSUE THREAD

**Issue by ersvltan** [netresearch/dhl-shipping-m2#10]
Hello,

DHL box at the bottom of the checkout is not updating after changing some settings in the "Shipping Services in Checkout" section.

Ways to reproduce:

1. Open DHL settings and turn off previous and set some new services in "Shipping Services in Checkout"
2. Click "Save" & clean the caches.
3. Go to the checkout and check the DHL box, the old services are still remaining, and there is no change.

**Comment by powli** [comment]
Hey @ersvltan, please check if you have also cleaned up your browsers application storage for the store in question, as the results from the service availability request are cached in the browser for the zip code/country combination.

**Comment by ersvltan** [comment]
@powli Ohh, how come that I forgot to check the browser cache. Yes, cleaning the browser cache solved the problem. Thank you!

Btw, is there any info about it in the documentation?

**Comment by ngolatka** [comment]
@ersvltan No, that's not in the documentation because we don't expect the configuration to be changed all the time.

Also, when a **new** cart (i.e. a new quote) is created, the services are not loaded from the browser cache. Your "problem" can really only occur for existing carts/quotes. As soon as the quote ID changes, the new service configuration is used.

**Comment by powli** [comment]
> Also, when a new cart (i.e. a new quote) is created, the services are not loaded from the browser cache. Your issue can really only occur for existing carts/quotes. As soon as the quote ID changes, the new service configuration is used.

Even changing the zip code or the country in the checkout would suffice.

**Comment by ngolatka** [comment]
Closing this, since there have been no further questions.

Not happy? Feel free to reopen this issue.
