### ISSUE TITLE
Improvement: Show parcel finder inactive, if not available

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-shipping-m2#12]
Hi,
we have activated the parcel finder option for our customers.
The option for finding parcel station is not shown in frontend UNTIL a complete address is filled out.
It would be better the parcel finder option is shown in a deactivated state or with a tooltip, that the parcel finder can be used if the address is filled out.
You can check this at https://shop.icletta.com
1. Put a product into the basket
2. Go to checkout
3. At the bottom of the onepage checkout you see only the parcel announcement option
4. After entering an address, the dhl shipping option box is reloaded and you can see the parcel finder option

**Comment by ngolatka** [comment]
Hello @template-provider 
This part is the important one:
> After entering an address, the dhl shipping option box is reloaded

It's not about the Location Finder itself. The entire shipping method block gets loaded after entering an address.

Correct me if I'm wrong, but I believe this has nothing to do with the DHL module itself. The decision which shipping methods are actually usable (DHL or others) is made by Magento itself, and it can only be made after the customer's address is known.

**Comment by template-provider** [comment]
> Hello @template-provider
> This part is the important one:
> 
> > After entering an address, the dhl shipping option box is reloaded
> 
> It's not about the Location Finder itself. The entire shipping method block gets loaded after entering an address.
> 
> Correct me if I'm wrong, but I believe this has nothing to do with the DHL module itself. The decision which shipping methods are actually usable (DHL or others) is made by Magento itself, and that decision can only be made after the customer's address is known.

Hi,
no the block itself is loaded before, but the parcel finder is missing.
After entering the address the parcel finder is added (with block reload).

Before entering address:
![Bildschirmfoto vom 2020-10-30 13-10-01](https://user-images.githubusercontent.com/25743167/97703996-e3e68100-1ab1-11eb-8d61-3ec762f661d2.png)

After entering address:
![Bildschirmfoto vom 2020-10-30 13-11-36](https://user-images.githubusercontent.com/25743167/97704035-f1037000-1ab1-11eb-844c-73f1367eb0ba.png)

If the parcel finder is visible, but inactive ... that would be nicer

**Comment by ngolatka** [comment]
The Location Finder (not parcel finder) is only available for Germany, that's why it can only be displayed after the address has been entered.

If it were displayed always (even as "inactive") it would almost certainly confuse people who order from other countries, making them wonder "why does that not work?"

**Comment by template-provider** [comment]
@ngolatka :
ok, that explanation is good for me .... I think the confusing part for me is now documentated in the issue #13 
the initial country was germany, but the parcel finder is not active
