### ISSUE TITLE
Problem with initial state of parcel finder

### ISSUE THREAD

**Issue by template-provider** [netresearch/dhl-shipping-m2#13]
We have a problem with initial state of the parcel finder.
If we go to checkout, we have selected a "default country "Deutschland".
The block with the shipping options is loaded but WITHOUT the parcel finder.
This problem may be the same regarding the issue before #12 

1. Product in Basket and proceed to checkout
=> Parcel finder is not visible and  Country is "Deutschland"
![Bildschirmfoto vom 2020-10-30 14-21-45](https://user-images.githubusercontent.com/25743167/97709847-442df080-1abb-11eb-83b6-d7b765489b4d.png)
2. Switch to country other than germany
=> Block is reloaded without parcel finder ... correct
![Bildschirmfoto vom 2020-10-30 14-22-44](https://user-images.githubusercontent.com/25743167/97709950-66277300-1abb-11eb-9117-9752b3bec8fb.png)
3. Switch back to "Deutschland"
=> Block is reloaded wit parcel finder ... correct
![Bildschirmfoto vom 2020-10-30 14-23-28](https://user-images.githubusercontent.com/25743167/97710020-7dfef700-1abb-11eb-9ee3-42214b3582ca.png)

I think the initial state/event is missing. The event for showing/reloading the block should be triggered after the page is loaded
and not only by changes from the country.
Greetings
Jan

**Comment by ngolatka** [comment]
Hello @template-provider , I tried to duplicate your issue, but I don't see it. For me, things look ok.

What I did is this:
* enable only DHL Shipping for checkout, no other shipping methods
* set default country to Germany
* put something in the cart and go to checkout
* scroll down to see the shipping method -> the entire DHL block is not visible yet
* start entering my name -> the AJAX spinner appears and the DHL block becomes visible
* whenever I changes something in my address

No switching of the country was necessary for me. As soon as the DHL block was visible, the button "Find Parcel Station" was always in it.

Tested on M2.3.5 with DHL module 1.2.0

I see a call to "estimate-shipping-methods" in the network tab of the browser dev-tools when I change the city or something. Does that not happen in your case?

**Comment by template-provider** [comment]
Hi,
we are using Magento 2.4.1 with PHP 7.4.
- enable only DHL Shipping for checkout, no other shipping methods
- set default country to Germany
- put something in the cart and go to checkout
but then
- scroll down to see the shipping method -> the entire DHL block is visible, but without the parcel finder.

like the first screenshot from my comment before

**Comment by mam08ixo** [comment]
I can only guess that the wrong country is used to load service data although "DE" is selected in UI. To validate, please

1. remove the `dhl_shipping_data_storage` entry from local storage
1. refresh the checkout page
1. monitor the request payload to `dhl/checkout-data/get`
1. let us know what you see

![01-local_storage](https://user-images.githubusercontent.com/1771622/98523317-12184d80-2276-11eb-9450-ff299a102cd7.png)
![02-network](https://user-images.githubusercontent.com/1771622/98523318-12b0e400-2276-11eb-8b18-0fdc9e2e269f.png)

**Comment by template-provider** [comment]
Hi,
the payload is:
```
{"countryId":"DE","postalCode":"64331"}
```
but the parcel finder is not active.
You can check it yourself directly on our website: https://shop.icletta.com

**Comment by template-provider** [comment]
Another thing is strange. I can change the country to BR (get call is triggered) and change back to DE (no call is triggered ... caching of the response before?), but after changing to DE the parcel finder is active (as mentioned in comments above)

**Comment by mam08ixo** [comment]
Thank you for the link to the website, that was helpful.

It appears that you have set a _default postal code_ for tax calculation in checkout.

`Stores → Configuration → Sales → Tax → Default Tax Destination Calculation → Default Post Code`

When you clear that field (and config cache, local storage entry), then everything should work as designed (service box loads **after** address data was entered). In my understanding, the default postal code is not necessary for tax calculation in Germany.

We may further investigate why the location finder is not displayed with default postal code configured, but the workaround should get you going for now. Please let us know about the result, thanks!

**Comment by template-provider** [comment]
Hi,
thx .... this change seems to work, now the dhl service box is loaded after any address data was entered.
Should I close the issue or keep it open?
```
We may further investigate why the location finder is not displayed with default postal code configured, but the workaround should get you going for now. Please let us know about the result, thanks!
```

**Comment by mam08ixo** [comment]
I am about to create a ticket in our internal issue tracker. As the original issue is worked around via store configuration, I close it here.

**Comment by ngolatka** [comment]
_Internal ref: DHLGW-1002_
