### ISSUE TITLE
Magento 2.4 support?

### ISSUE THREAD

**Issue by oleksii-lisovyi** [netresearch/dhl-shipping-m2#17]
Hi!

Is there any way to get a module version compatible with Magento 2.4.1?

Currently the old module https://github.com/netresearch/dhl-module-shipping-m2 is incompatible because magento/framework version is compatible with only M2.2/2.3.

**Comment by ngolatka** [comment]
Hello @oleksii-lisovyi 
I don't really understand the problem. We released https://github.com/netresearch/dhl-shipping-m2/releases/tag/1.4.0 recently and I installed it on M2.4.1 without trouble.

Please note that this module https://github.com/netresearch/dhl-module-shipping-m2 is not the same as this one https://github.com/netresearch/dhl-shipping-m2

https://github.com/netresearch/dhl-module-shipping-m2 is a legacy module which will not be updated any further.

**Comment by oleksii-lisovyi** [comment]
Hello @ngolatka!

Thank you for the reponse and the clarification. There was no link from the legacy moduel to the new one, so I was a bit confused. Now everything is clear.
