### ISSUE TITLE
max_package_weight

### ISSUE THREAD

**Issue by alexandergolz** [netresearch/dhl-shipping-m2#19]
We use (or maybe misuse) the weight property of articles to calculate shipping costs via tablerate. This is not the real weight, but in most cases a much higher number. With the old extension this was no problem. This new extension seems to have a max_package_weight defined in https://github.com/netresearch/dhl-module-carrier-paket/blob/3a64acc69a14fd019319a70449ad49aadf5d1a82/etc/config.xml#L14. Could this value become configurable in the backend?

**Comment by mam08ixo** [comment]
This is a very special requirement that we will not consider in our module code. However, you should be able to replace that value using a database or `config.php`/`env.php` value, whatever suits you best.

**Comment by ngolatka** [comment]
@alexandergolz I guess you are aware that all DHL modules transmit the weight to the DHL API. Does this not cause much higher postage (porto)?

DHL is usually not very happy if the transmitted parcel weight differs grossly from the actual weight (which they do check).

**Comment by alexandergolz** [comment]
@ngolatka: We really only send maybe 10-20% actually with DHL, for the rest we simply do not generate the label. And of course we use the real weight when generating the label. It'a sll mabye somewhat convoluted, but it works suprisingly well with our small sales.

> @alexandergolz I guess you are aware that all DHL modules transmit the weight to the DHL API. Does this not cause much higher postage (porto)?
> 
> Also, DHL is usually not very happy if the transmitted parcel weight differs grossly from the actual weight (which they do check).
