### ISSUE TITLE
Unable to install it, as if it doesn't exist on Magento's repository

### ISSUE THREAD

**Issue by kaourimo** [netresearch/dhl-shipping-m2#2]
Whenever I do 
`composer require dhl/shipping-m2:1.0.0`

I get an error telling me 
```
[InvalidArgumentException]                                          
Could not find package dhl/shipping-m2 in a version matching 1.0.0
```

Is it not on the Magento repo?

**Comment by mam08ixo** [comment]
The extension is available on https://repo.magento.com/ as soon as you "purchase" the [extension on Magento Marketplace](https://marketplace.magento.com/dhl-shipping-m2.html). You have to use your account's access keys to install it.

Please follow the [Magento extension installation procedure](https://devdocs.magento.com/extensions/install/).

**Comment by ngolatka** [comment]
If anyone runs into the same problem in the future, here's an additional tutorial about that: https://dhl.support.netresearch.de/support/solutions/articles/12000056624

**Comment by kaourimo** [comment]
I fixed the issue I had by running this command:
`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer`

Okay, now I have another issue, after installing the module by following the instructions, the website is broken and gives a HTTP Error 500 when visiting it.

This is what I see on the apache2 error.log:
`[Thu Jun 04 20:21:09.234983 2020] [php7:error] [pid 25893] [client 37.36.157.205:41440] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Dhl\\ShippingCore\\Api\\Util\\UnitConverterInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121\nStack trace:\n#0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Dhl\\\\ShippingCor...', Array)\n#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Dhl\\\\ShippingCor...')\n#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Dhl\\\\ShippingCor...')\n#3 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Dhl\\\\ShippingCor...', Array)\n#4 /var/www/html/vendor/magento/module-quote/Model/Quote/Address/TotalFactory.php(40): Magento\\Framework\\ObjectManager\\ObjectManager->create('Dhl\\\\ShippingCor in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121, referer: https://staging.ikarustech.com/
`
How can I fix this? Thank you :)

**Comment by mam08ixo** [comment]
Before we go any further, are you aware that this module can only be used for shipping from Germany?

**Comment by kaourimo** [comment]
nope, are there are plans to support international shipping?

**Comment by mam08ixo** [comment]
It does support international shipping, but only for shipping **origins** in Germany. There are plans to add further DHL divisions to the project which cover other shipping origin countries. However, no fixed roadmap or ETA exists. DHL Parcel Germany is what we offer for now, as explained on the [Magento Marketplace extension page](https://marketplace.magento.com/dhl-shipping-m2.html#description) and the [project wiki](https://github.com/netresearch/dhl-shipping-m2/wiki).
