### ISSUE TITLE
length x width x height

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#20]
Just a very minor feature request to make usage more streamlined:

In some cases dhl-shipping-m2 makes entering parcel dimensions mandatory.
I just noticed that the fields are ordered  **width-height-length** while
the common order is always   **length/longest side - width - height (shortest side)**
Also cardboard boxes are s**old in millimeter while the input is in centimeter.**
People would usually copy&paste the size from one of their orders of cardboard boxes.

**Comment by mam08ixo** [comment]
I agree with updating the input sort order.
Units of measurement will not be changed. Magento uses cm/in and we will stick to that.

**Comment by mam08ixo** [comment]
In [DHL Shipping version 2.0.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.0.0), the dimension inputs in packaging popup are now in the desired order.
