### ISSUE TITLE
Customs Reference Numbers

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#22]
In the DHL brexit documentation it is not requires but recommed to enter one's EORI number.
https://www.dhl.de/brexit

Usually an EU company has but 1 EORI number issued by the country they are in.
Sometimes a second for a non-EU origin country they have a second shipping facility in.
The input in dhl-shipping-m2 requires the user to enter the EORI ("Customs Reference Numbers")
separately for each destination country. So for the usual case, you have to enter the same number about 200 times.

This way of handling the input seems suboptimal.

**Comment by mam08ixo** [comment]
Considering only the EORI number would simplify things, correct. However, there are certain reference numbers that are required for specific destination countries only and that is why the input looks like that. I do not see that being changed to be honest. And I also do not see someone configuring the EORI number for all countries in the world. Setting it for the top ten or twenty should suffice, shouldn't it?

**Comment by YiffyToys** [comment]
I guess you can enter it manually in the create-postage dialogue too, when missing.
Just like having HS codes missing in some products.
Not optimal but possible.

**Comment by mam08ixo** [comment]
Yes, if no default value is configured for the current route, then the value can still be added in packaging popup.

Closing this now as there is no actionable task.
