### ISSUE TITLE
Updating from dhl-module-shipping-m2 with dependcies

### ISSUE THREAD

**Issue by baali** [netresearch/dhl-shipping-m2#24]
We have an existing setup of magento version: `2.3.6` and now obsolete [dhl-module-shipping-m2](https://github.com/netresearch/dhl-module-shipping-m2) module. My first attempt to update module by directly upgrading `composer.json` didn't work, I was not able to add items to a cart(error I got was: `quote couldn't be saved`)

I followed comments on other closed issue and as pointed out [here](https://github.com/netresearch/dhl-shipping-m2/issues/3#issuecomment-642247722) If I remove the data manually I am able to upgrade to this release. 

But we are using another module: [DHL Label Status extension](https://github.com/netresearch/dhl-module-label-status-m2) and it is tied to obsolete extension. When I try to remove data just for `./bin/magento module:uninstall --remove-data Dhl_Shipping`, I can't because of `Dhl_LabelStatus` dependency. 

Can this be resolved without removing data? Is there an alternate to `Dhl_LabelStatus` that works with latest `Dhl_Shipping` module?

**Comment by mam08ixo** [comment]
The label status feature is a native part of the current `Dhl_Shipping` extension. This additional package is no longer needed. You can safely proceed removing the label status module and the legacy shipping module.

**Comment by baali** [comment]
When I upgraded the module by dropping the data, the column for `DHL Label Status` was no longer there in the magento order grid and I also looked in the `Columns` section to restore it but didn't find it. I will confirm this once more. 

Following up on removing the data, is that necessary? Is there a way around it? Ideally I would like to avoid that.

**Comment by mam08ixo** [comment]
You can migrate the old data as explained in the [Wiki](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#migration-from-previous-dhl-versenden-extension). But eventually the legacy module's data must be removed, yes.

**Comment by ngolatka** [comment]
What can happen if you don't remove the data? [This](https://dhl.support.netresearch.de/support/solutions/articles/12000077379).

**Comment by baali** [comment]
Both the links, to the wiki and issue on not removing the data are helpful. Thank you @mam08ixo and @ngolatka. I am following the steps in wiki to install ` Post & DHL Shipping extension version 1.1.0`. Can I keep this thread open to resolve issues(if any) I can't resolve in the process of migrating the data?

**Comment by ngolatka** [comment]
If you encounter things that are likely to affect others, yes, that would make sense.

If you have other problems not related to this, you can go here: https://dhl.support.netresearch.de/support/tickets/new (ends up on my desk anyway).

**Comment by baali** [comment]
Hello,

I followed the instructions on wiki, to port the data. As wiki suggested:

> make sure to install the new Post & DHL Shipping extension version 1.1.0. 

    composer require dhl/shipping-m2:1.1.0
    ./bin/magento setup:upgrade
    ./bin/magento setup:di:compile
    # Port the data:
    php ./bin/magento dhlgw:migrate-attribute

At this stage I uninstalled the modules: `Dhl_Shipping` and `Dhl_LabelStatus` by also deleting the data:

    ./bin/magento module:uninstall --remove-data Dhl_Shipping Dhl_LabelStatus

Then I removed older module and upgraded to latest `1.5` version:

    composer remove dhl/module-shipping-m2
    composer require dhl/shipping-m2
    ./bin/magento setup:upgrade
    ./bin/magento setup:di:compile
    ./bin/magento setup:static-content:deploy

Beyond this, I am not able to confirm the data transfer of the attributes. Additionally:
1. In magento order grid I can see `DHL Label Status` but that column just shows, `Not Available`. I can't seem to find a way to enable them again. 
2. Previously under `Stores -> Configuration -> Sales -> Shipping Methods` I would see `DHL Shipping` to configure Shipping account details, that are no longer visible. In my `config.php` I see that line: `'Dhl_Shipping' => 1,` has been removed. Do I need to again `install` the module `Dhl_Shipping` after doing the step of installing `shipping-m2` module? Or the additional modules like: `Dhl_Ui`, `Netresearch_ConfigFields` supposed to cover for them? If yes, where to setup DHL account settings again to be able to create shipping labels?

I was not able to find my way through the [user-guide](https://marketplace.magento.com/media/catalog/product/dhl-shipping-m2-1-0-0-ce/user_guides.pdf) to get the setup working again.

**Comment by ngolatka** [comment]
Please note there's also a quite comprehensive [Knowledge Base](https://dhl.support.netresearch.de/) for the module, covering both the legacy and the current module. Regarding the status "_Not available_" please see [this article](https://dhl.support.netresearch.de/support/solutions/articles/12000040515).

And about the configuration: it is now in a different area, which is also [explained in the documentation](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#module-configuration).

**Comment by mam08ixo** [comment]
Please read the Wiki/documentation carefully. There is also a [chapter about account configuration](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#production-requirements).

The label status values are not migrated and will only be populated for new orders placed with the new module. Attribute values (HS code and item export description) should be copied to the new EAV attributes though.

If the label status column shows _Not Available_, then data migration did not succeed (you )

**Comment by baali** [comment]
Thanks a lot for the pointers and followup. I was able to get the plugin working.
