### ISSUE TITLE
Fehler bei Auswahl der Packstation

### ISSUE THREAD

**Issue by Assambra** [netresearch/dhl-shipping-m2#27]
Beim Ersten ausfüllen der Daten im Checkout wird der Button Packstation finden nicht angezeigt. Erst nach dem die Seite über den Browser neu geladen wird, wird der Button angezeigt.

Wenn die Checkout Daten vorhanden sind und man die Adresse ändert wird das Popup nicht immer mit der neuen Adresse befüllt sondern nimmt die alten Daten. (Es ist nicht immer reproduzierbar)

Des weiteren kommt es vor das die Versandart vorausgewählt ist und manchmal nicht das hat auch auswirkungen auf das Popup Packstation finden und die enthalten Daten z.B. Land. aber auch andere Daten

Wenn ich ein Custom Theme benutze wird das Land nicht ausgewählt und somit kann kein Auswahl der Packstation getroffen werden.

Ich benutzte Magento Version 2.4.1 und 2.4.2 auch versucht in kombination dhl-shipping-m2 v 1.5.0 und 1.5.0

Wie gesagt es ist schwer zu reproduzieren oder eine klare Aussage zu treffen wann weshalb warum auf jedenfall funktioniert es bei mir nicht wie es soll.

**Comment by Assambra** [comment]
Thank you for your answer. It was a typo with 1.5.0 and 1.5.0, it should be called 1.5.0 and 1.5.1. In short I already tried it. It would be nice if you could give me a tip about what it might be. You know your module better than I do.

**Comment by Assambra** [comment]
As I have already written, the main problem is that he does not find the country or does not get the correct values.

**Comment by mam08ixo** [comment]
What do you mean by "does not find the country"?  Without specifying country and postal code, the DHL shipping method (with its service box, including Packstation button) should not even be available in checkout. Did you configure something in `Sales → Tax → Default Tax Destination Calculation` maybe that sets the quote address to invalid defaults?

**Comment by ngolatka** [comment]
That looks very broken to me. Here's what a working popup should look like:
![image](https://user-images.githubusercontent.com/7393538/110639826-727db400-81b0-11eb-8033-d4e9d3cb1406.png)

Note that you are also missing the stuff I marked in red on my screenshot.

Is your screenshot based on a default Magento checkout, or a customized one? If it's customized, please check again with a vanilla checkout. Also check the browser console for JS errors and other things.

By the way: I just verified that it works perfectly fine in version 1.5.1.

**Comment by mam08ixo** [comment]
The country options are taken from local storage. Please check how this looks in your case. You may also debug 

![country_options](https://user-images.githubusercontent.com/1771622/110640480-2717d580-81b1-11eb-814c-790e7cb1c3fd.png)

You may also debug the JS component:

https://github.com/netresearch/module-shipping-ui/blob/2c58a73df240433b82e9bdbc1e59b40e81b91f5c/view/frontend/web/js/view/input/locationfinder.js#L57

**Comment by Assambra** [comment]
![Unbenannt-1](https://user-images.githubusercontent.com/6276777/110647297-030bc280-81b8-11eb-8695-9f907d0f80d8.jpg)

**Comment by mam08ixo** [comment]
Looking good to me. Now you only have to find out why the country options are not set accordingly.

A timing issue maybe? Parcel shop component initialized before local storage is populated via `checkout-data/get` REST call?
https://github.com/netresearch/dhl-module-ui/blob/1.2.3/view/frontend/web/js/action/checkout/webapi/get-checkout-data.js#L42

**Comment by Assambra** [comment]
First of all, thanks for your help. Debugging a website is beyond my ability. I hoped there was something obvious to fix. I will then contact the person who created the theme and hope he can help.

The only thing that struck me is i have several DE Plz Objects is this normal? like DE12345 DE72805 and so on.

**Comment by mam08ixo** [comment]
Yes that is expected behavior. For every postal code you enter in checkout, an entry in the local storage will be made. That is because the available services and service options can differ, for instance next possible delivery date in rural or metropolitan areas.

**Comment by Assambra** [comment]
I would like to give you a short feedback. It works as it should now. But unfortunately I can't say 100% what it was. But for others who may have a similar problem. I accelerated the site and for this I installed the Apache mod_http2. I can't say how it all goes together, but I'm happy that it works now.
Thanks to everyone who supported me.

**Comment by Assambra** [comment]
Afterwards I tried it again and noticed that it didn't work again today. It stays weird. If I know more I will give you a feedback.

**Comment by ngolatka** [comment]
_internal Ref: DHLGW-1091_

**Comment by Assambra** [comment]
I would now like to give a small update. I am now using a new theme. The same error here. Both themes have an AJAX shopping cart solution, only if I deactivate it does work. Maybe you should take a closer look at the problem with your Extension and AJAX Shopping Cart. I hope you can find the Problem and fix it so that others and me can use it together.

**Comment by madonzy** [comment]
I have the same problem on M2.4.2 and I also checked the dev console. There's a CSP issue when loading the map.
<img width="1679" alt="Screen Shot 2021-08-03 at 14 19 41" src="https://user-images.githubusercontent.com/5281020/128014306-9bc88be2-b2d6-4f6f-9fab-a573f2d5e93c.png">

**Comment by mam08ixo** [comment]
@madonzy We are still struggling to understand how the map can be initialized with empty country dropdown. Any findings or details may help (module version, guest/registered checkout, checkout customizations, steps to reproduce, etc.)

If you have a publicly available instance where the issue can be reproduced, you may also add the details here or send them to the [extension support|https://github.com/netresearch/dhl-shipping-m2/blob/2.0.1/README.md#support].

Is the CSP issue is related? Is it actually map content that is not being loaded?

**Comment by Assambra** [comment]
@madonzy do you have a AJAX Shopping Cart solution? If yes try to disable it, clear cookies site cache and so on and try again.  This is the problem in my case if i disable this cart solution it works on my page.
The Problem still exist on my site and the error is the same. It cames from the empty country.

**Comment by Assambra** [comment]
![Packstation](https://user-images.githubusercontent.com/6276777/128151521-0324bce8-2972-4637-80b4-e6ad62858f28.jpg)

**Comment by mam08ixo** [comment]
Thank you, I can confirm that we need to add a CSP whitelist policy for mapbox but this is not the cause of the issue.

**Comment by Assambra** [comment]
@madonzy please try to reproduce any AJAX Shopping Cart solution(try some free one from the Magento Marktplace maybe there will be the same Error).
I have two Themes with a different AJAX Shopping cart solution included and on both Themes the only way was to disable it and the Packstation/no country problem are gone. If you want invastigate you can try it on my page give me a shout.

**Comment by mam08ixo** [comment]
@Assambra In your shop, missing `directory-data` in local storage causes the problem.

![local_storage__directory_data](https://user-images.githubusercontent.com/1771622/128170083-ff58d27e-afed-40a5-bd5d-52546a65f3f2.png) vs. ![local_storage__no_directory_data](https://user-images.githubusercontent.com/1771622/128170103-8df5259f-435f-4870-8cbc-daec29cf06b5.png)

No idea why `directory-data` is not present or why it is not loaded when being accessed but we will come up with a workaround.

**Comment by Assambra** [comment]
I updated the post before and the solution is disabled try again and all will work

**Comment by mam08ixo** [comment]
@Assambra By the way, the missing directory data in your store also causes the country name not being displayed in the checkout payment step (billing and shipping address).

**Comment by Assambra** [comment]
Sorry for the late reply and thanks for the hint. I would not have noticed because I only send within Germany and have excluded all other countries. So I didn't even look for something like that.

**Comment by mam08ixo** [comment]
We now try to load the directory data explicitly if it is not already available. Please check if  [DHL Shipping v2.1.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.1.0) solves the issue for you.

**Comment by Assambra** [comment]
Unfortunately, it doesn't work as expected. It only works if the website is reloaded once.

**Comment by mam08ixo** [comment]
Okay we could not test this because we were not able to replicate the issue. I suggest you fix the root cause and make sure that directory data is loaded when the customer enters checkout. Maybe our (re)loading of directory data is too late for rendering the component. This is our change that was supposed to fix the issue: https://github.com/netresearch/module-shipping-ui/blob/2.0.3/view/frontend/web/js/model/checkout/country-options.js#L18

**Comment by ngolatka** [comment]
No further activity -> issue closed.
