### ISSUE TITLE
Error after installation - ExportDescription does not exist

### ISSUE THREAD

**Issue by codingcoast** [netresearch/dhl-shipping-m2#3]
Magento version 2.3.3

I did the following:
Replaced this lines in composer.json:

```
"dhl/module-label-status": "^1.1",
"dhl/module-shipping-m2": "^0.11",
```
with:

`"dhl/shipping-m2": "^1.0.0",`

Then
```
php composer.phar update
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:flush
php bin/magento cache:clean
```

When I access the frontend or backend I get the following Error:

`main.CRITICAL: Class Dhl\Shipping\Model\Attribute\Backend\ExportDescription does not exist {"exception":"[object] (ReflectionException(code: -1): Class Dhl\\Shipping\\Model\\Attribute\\Backend\\ExportDescription does not exist at [...]/vendor/magento/framework/Code/Reader/ClassReader.php:19)"} []`

**Comment by ngolatka** [comment]
@codingcoast Can you confirm that the instructions from @mam08ixo resolved your problem? If yes, please close this issue.

**Comment by codingcoast** [comment]
Didn't know that this procedure can cause problems.
I tried it with uninstalling first and it seems to work.
Thank you
