### ISSUE TITLE
"Parcel Station Delivery" with someone else's DHL Post Number selected

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#30]
We just tried to create postage as usual for a delivery to a regular house address in Germany
and noticed that the "Shipment Setup" dialog would show
"[X] Parcel Station Delivery" selected and
a DHL Postnummer.
The delivery address of the order didn't contain any DHL Postnummer and nothing in the customer's details show one. 

![Screenshot 2021-04-03 151911](https://user-images.githubusercontent.com/52350973/113479537-fc5b2d00-948f-11eb-9a88-ca7d428f926a.png)

**Comment by YiffyToys** [comment]
We edited "DHL Recipient Street, setting a "_" for supplement to many sure it was overwriten but this keps coming up in the dialog.

**Comment by YiffyToys** [comment]
Looks like the postnummer WAS entered by the customer during checkout in the Packstation-dialog, 
(supposedly then that dialog closed and a home address entered),
but the DHL section below the delivery address in the Admin-UI didn't show that it was entered.
That caused some confusion and panic as to where this number suddenly came from.

**Comment by mam08ixo** [comment]
The _DHL Recipient Street_ section on the order details page in admin panel does not show the selected pickup location, neither does the address edit form.

There is a _DHL Services_ section below the _Payment Information_ that displays service details, including selected Packstation or post office. If you still think there is an issue, please re-open and explain what you expected to happen and what actually happened. Thank you!

![dhl_services](https://user-images.githubusercontent.com/1771622/114372456-ddd8ee00-9b81-11eb-862c-b8909b0b00c8.png)

**Comment by YiffyToys** [comment]
Thanks, I actually never noticed that as it's in the same style as the (very lengthy in case of PSD II credit card) payment block .
