### ISSUE TITLE
UK > 125 GBP not handled as export

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#31]
For orders >125 GBP (according to ) to the UK (except northern ireland = ZIP codes starting with "BT"), the customer pays VAT and duties and the seller
has to do the usual export paperwork (just CN22/CN23 for orders <1000eur).
Looks like the backend handles that case but the frontend is missing the input fields
for an export and handles it like an EU parcel.

(Magento VAT rules can't handle value dependent VAT rules yet either, so we currently have a minimum order size for UK customers.)

![Screenshot 2021-04-17 141748](https://user-images.githubusercontent.com/52350973/115112892-d6ea1b00-9f87-11eb-8e5b-ced0ec037bb5.png)

HMRC rule:

https://www.gov.uk/government/publications/changes-to-vat-treatment-of-overseas-goods-sold-to-customers-from-1-january-2021/changes-to-vat-treatment-of-overseas-goods-sold-to-customers-from-1-january-2021

official exchange rates for the 125 GBP rule:
https://www.gov.uk/government/publications/hmrc-exchange-rates-for-2021-monthly

**Comment by powli** [comment]
Hey @YiffyToys ,

The route dependent input field availability is dependent on the EU countries configuration in the Magento configuration. Have you checked if UK is part of EU in the affected shop?

**Comment by YiffyToys** [comment]
Damn.
I thought we had that on the checklist back at the 1st of January.
Thanks for the hint.
