### ISSUE TITLE
DHL custom order totals in PDF (again)

### ISSUE THREAD

**Issue by OvalMedia** [netresearch/dhl-shipping-m2#35]
Since you just closed the issue without giving me the opportunity to respond, I'm gonna go again.

Referring to: https://github.com/netresearch/module-shipping-ui/issues/1

I already am on the latest version of `dhl/shipping-m2`. My composer.lock reports version 1.5.1.
So what can I do to get the proper items inside a totals.phtml?

**Comment by ngolatka** [comment]
> My composer.lock reports version 1.5.1

That is not the latest version of the DHL Shipping metapackage. The latest version is 2.0.1

Please update from 1.x to 2.x (here's [how to do that](https://dhl.support.netresearch.de/support/solutions/articles/12000078910)). That should already pull the fix into your system.

**Comment by mam08ixo** [comment]
DHL Shipping 1 and 2 now render the service fee custom total in PDF files.

If you want to display them on other pages, then have a look at the layout files. Examples:

* DHL Shipping v1: https://github.com/netresearch/dhl-module-ui/blob/1.2.3/view/adminhtml/layout/sales_order_view.xml#L23-L25
* DHL Shipping v2: https://github.com/netresearch/module-shipping-ui/blob/2.0.2/view/adminhtml/layout/sales_order_view.xml#L23-L25

**Comment by OvalMedia** [comment]
@mam08ixo : thank you, that's what I needed.

**Comment by mam08ixo** [comment]
So can we close this now?

**Comment by OvalMedia** [comment]
Yes
