### ISSUE TITLE
Checkout not working after upgrade from 2.2.9 to 2.4.2-p1

### ISSUE THREAD

**Issue by OvalMedia** [netresearch/dhl-shipping-m2#36]
I am currently upgrading a store that is still running on Magento 2.2.9. Of course it is also running the old dhl shipping module.
So I upgraded on my local system and everything seems to work fine except when I go to cart or the checkout.

I can still access the cart page but it is already odd that the cart's summary does not show up. But other than that there are no error messages (e.g. in JS console) or log entries (var/log/, var/report/). Btw... I enabled error reporting in index.php.

When I go to checkout I can see the shop's header and footer but in the middle of the page a spinner keeps spinning forever and nothing else happens. Also no error messages or log entries.

The same behaviour occurs when switching to magento's luma theme.

When I disable all dhl/shipping-m2 modules everything works fine.

So my question is: how can I narrow down the issue? Is there anything I can do to maybe rest all the DHL settings and start over? Since there are no error messages or log entries I am kind of lost here.

Thank you.

**Comment by mam08ixo** [comment]
Did you also watch out for 500 errors in the network tab when entering cart or checkout?

**Comment by OvalMedia** [comment]
Yes, I checked everything. All files came fine with status code 200.

**Comment by mam08ixo** [comment]
okay, how about nginx/apache/php log (you did not mention that explicitly).

**Comment by OvalMedia** [comment]
Also nothing :(

**Comment by mam08ixo** [comment]
If you had the old DHL Shipping module installed and did not do so already, follow the [uninstallation guide](https://github.com/netresearch/dhl-module-shipping-m2/blob/0.11.1/README.md#manual-steps).

To reset the new module settings, clearing all `carriers/dhl%` entries from `core_config_data` should be enough. But I doubt that a misconfiguration can lead to the reported behaviour.

**Comment by OvalMedia** [comment]
You are right, that did not make a difference. But meanwhile I found out there seems to be in incompatibility with the module Aheadworks Reward Points. I just disabled that (with DHL shipping enabled) and cart/checkout are both working again.
Will keep you updated in case I find out more.

**Comment by ngolatka** [comment]
No further activity -> issue closed.
