### ISSUE TITLE
Wrong calculation of shipping costs

### ISSUE THREAD

**Issue by Assambra** [netresearch/dhl-shipping-m2#38]
Shipping costs are incorrectly calculated. Example: Shipping weight per item 0.150 kg. Customer orders 20 items, it weighs 3,000 kg, but a 5kg package will be charged and that is wrong. up to 3,000kg and only from 3,0001 kg, the 5kg package should be triggered, as it is calculated that way by DHL.

**Comment by mam08ixo** [comment]
The shipping module itself does not calculate shipping costs at all. It is your responsibility to set up flat rate, table rates, or any other rates provider module according to your business needs.

**Comment by Assambra** [comment]
Ok, thanks, I have adjusted the tablerate to DEU, *, *, 3.001,6.9900. it works as expected. I thought I would have played it through when setting up the shop and it would have worked. Sorry for the false report.
