### ISSUE TITLE
Releasing a new version on packagist.org causes problems if the version is not also released in repo.magento.com as well

### ISSUE THREAD

**Issue by poebel** [netresearch/dhl-shipping-m2#41]
Currently version 2.2.0 is only available on packagist.org and not (yet?) in the magento repo (repo.magento.com).

This leads to an errror from the [Magento composer dependency version audit plugin](https://github.com/magento/composer-dependency-version-audit-plugin).

```
  [Exception]
  Higher matching version 2.2.0 of dhl/shipping-m2 was found in public repository packagist.org
                               than 2.1.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,
                               please investigate and update package requirement to match the version from the private repository

```

**Comment by mam08ixo** [comment]
The latest module version is now available from both repositories, Packagist and Marketplace.
