### ISSUE TITLE
Magento 2.4.4 compatibility

### ISSUE THREAD

**Issue by plastikschnitzer** [netresearch/dhl-shipping-m2#44]
I did a first test update to Magento 2.4.4 and ran into the following conflict:

```
  Problem 1
    - dhl/shipping-m2 2.5.0 requires dhl/module-carrier-paket ~2.5.0 -> satisfiable by dhl/module-carrier-paket[2.5.0].
    - dhl/module-carrier-paket 2.5.0 requires monolog/monolog ^1.17 -> found monolog/monolog[1.17.0, ..., 1.27.0] but it conflicts with your root composer.json require (^2.3).
    - Root composer.json requires dhl/shipping-m2 ^2.5 -> satisfiable by dhl/shipping-m2[2.5.0].
```

Using monolog/monolog version 1.17 as required by dhl/module-carrier-paket module is not possible as Magento 2.4.4 requires at least version 2.3. Is it safe to use this version also with dhl/module-carrier-paket?

**Comment by chequille** [comment]
Facing similar problem, as after updating Magneto to 2.4.4 when running setup:upgrade I get the following error:

PHP Fatal error:  Class Dhl\Paket\Model\Webservice\ShipmentService contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Dhl\Sdk\Paket\Bcs\Api\ShipmentServiceInterface::validateShipments) in /var/www/html/magento/vendor/dhl/module-carrier-paket/Model/Webservice/ShipmentService.php on line 16

Could it be, that I run a too old DHL version (1.1.1)?
Do I have to run some updates before updating to 2.4.4

And second problem as plastikschnizer does hhave I guess: updating DHL module gives as well errors when I treid this:
  Problem 1
    - Can only install one of: dhl/module-carrier-paket-returns[2.1.0, 1.1.1].
    - Can only install one of: dhl/module-carrier-paket-returns[2.1.0, 1.1.1].
    - Can only install one of: dhl/module-carrier-paket-returns[2.1.0, 1.1.1].
    - dhl/shipping-m2 2.5.0 requires dhl/module-carrier-paket-returns ~2.1.0 -> satisfiable by dhl/module-carrier-paket-returns[2.1.0].
    - Installation request for dhl/shipping-m2 ^2.5 -> satisfiable by dhl/shipping-m2[2.5.0].
    - Installation request for dhl/module-carrier-paket-returns (locked at 1.1.1) -> satisfiable by dhl/module-carrier-paket-returns[1.1.1].

Please advise.
BR
Chequille

**Comment by mam08ixo** [comment]
Magento 2.4.4 was just released and we do now begin to work on compatible module versions. The current Post & DHL Shipping version 2.5.0 is not expected to be compatible.

**Comment by ngolatka** [comment]
_internal ref: DHLGW-1172_

**Comment by mam08ixo** [comment]
Deutsche Post & DHL Shipping 2.6.0 with M2.4.4 support is now available at [Magento Marketplace](https://marketplace.magento.com/dhl-shipping-m2.html) and [GitHub](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.6.0).
