### ISSUE TITLE
 Shipping Label Automation send mail

### ISSUE THREAD

**Issue by in-session** [netresearch/dhl-shipping-m2#45]
Hello together,

would it be possible for you to add another function for the module? 

Currently I have not found a way to send the generated shipping labels to a specific email address. 
This would be very helpful to reduce the amount of work. For example, all delivery bills are sent to a specific e-mail address as an attachment and automatically printed from there. We would also like to have this for the labels, which are generated automatically.

Best Regards Christoph

**Comment by ngolatka** [comment]
@in-session I'm not quite sure what you are trying to accomplish. Why do you want to send the shipping labels somewhere via email? They are intended to be used by the merchant to put them onto the box during processing the customer's order.

Did you actually mean the **return** shipping labels? Those can be created on-demand by the customer in their account.

**Comment by in-session** [comment]
@ngolatka
Thanks for your feedback, currently it is only possible to download the label via admin or DHL interface. 
We have a print server that automatically prints the attachment for all incoming mails. Therefore, the basic idea would be to say that after creating the label, the label is automatically sent to a specific email, for example shipment.documents@domain.com.
This gives the bearing the right label right away, without you having to trigger anything. I also think that this is practical without having a special printing service.

**Comment by ngolatka** [comment]
That sounds like a useful feature. We'll have a look into it and talk to DHL, if necessary.

Thanks for the suggestion @in-session !

**Comment by ngolatka** [comment]
_internal ref: DHLGW-1240_

**Comment by mam08ixo** [comment]
Hi @in-session,

the idea is to trigger a simple text email on the `save_after` event, with the shipping label attached, to one of the email identities defined in _General → Store Email Addresses_. In the DHL configuration, all it takes is to enable the feature and select one of these identities as email receiver. Would this work for you?

**Comment by in-session** [comment]
@mam08ixo 

That sounds good, but I would suggest to use a separate field for the mail address and not the defaults adresses. I think just for the sending of the labels this should go to a diffrent mail address, like warehouse or some else.
In most cases we work with bcc, which makes no sense for the labels.

**Comment by mam08ixo** [comment]
@in-session Sorry, I do not get your point. The store email addresses config offers five identities in standard Magento. One of them could be used for the printer service, e.g. the "Custom Email 1" identity, no?

**Comment by mam08ixo** [comment]
But we could as well add the email address / addressee name to the DHL config for this purpose, no big deal.

**Comment by in-session** [comment]
@mam08ixo
Yes that would also be a good idea.

**Comment by mam08ixo** [comment]
The requested feature is available in the latest extension version, see [documentation](https://github.com/netresearch/dhl-module-carrier-paket/wiki/Documentation-English#how-to-e-mail-shipping-labels).
