### ISSUE TITLE
Doesn't print "supplement" part of street address

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#46]
An input address line for a US address
"%housenb% %street%, Apt #%apt%
gets broken up into

Street Name: %street%
Street Number: %housenb%
Supplement: "Apt #%apt%"

But in the resulting label the supplement=apartment number is not printed as part of the label.
Causing an already expensive 36.13€ parcel to be returned with an additional 20€ return fee.

**Comment by ngolatka** [comment]
@YiffyToys  Do you see the supplement-part (addressAddition) actually getting transmitted to DHL in the SOAP request?

If you see the apartment data in the request, I suspect this is (once again) the [problem we already had in the past](https://dhl.support.netresearch.de/support/solutions/articles/12000032016), meaning DHL decides based on the destination country if the supplement gets printed on the label or not.

**Comment by YiffyToys** [comment]
Seems to be that known issue.
