### ISSUE TITLE
Feature request: Auslieferungsnachweis 

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#47]
It would be a very handy feature if the shipping-M2 module would not only download the postage
but also the "Auslieferungsnachweis" (export certification) of shipments.
So users don't forget to manually download and archive them for each and every shipment destined for other EU or non-EU countries.

**Comment by ngolatka** [comment]
I'm not 100% sure what you are referring to. Also I haven't heard this request in support.

Do you mean the tracking information (independent of the destination country)? Or something else? I'm not aware of a document called "export certification" (yet). "Export" sounds like something related to shipments with customs declaration, but that makes only limited sense in my head.

If you need to know the shipping status, e.g. to resolve disputes with a customer who claims not to have received their shipment, there's the old [DHL Track & Trace portal](https://nolbusiness.dhl.de/nextt-online-business/jsp/login.do) and also an upcoming feature inside the Business Customer Portal.

**Comment by YiffyToys** [comment]
Yes, the pdf with the tracking information, proving that the parcel was actually delivered to a place outside Germany.
Merchants are required to archive it together with the receipt received when handing in a parcel to be eligible for VAT-free export to non-EU countries (and to not double pay German VAT and the destination-country VAT for EU-countries in case of O.S.S.).

In Geschäftskundenportan it's this one in "Sendungsliste"
![grafik](https://user-images.githubusercontent.com/52350973/172790099-55e11418-5d33-4bf2-88f2-81f88d0892de.png)

**Comment by mam08ixo** [comment]
Hi @YiffyToys, please configure a report "Versendungsnachweis" in the _Business Customer Portal_ or contact your DHL sales representative for further assistance.

Also take a look at the "Reports herunterladen" page if there is something available already that suits your needs.

![image001](https://user-images.githubusercontent.com/1771622/172814698-8f9b77e2-7fa7-4415-ad9e-b5c8f7e812e2.png)

It seems like your request cannot be done via the _Business Customer Shipping_ API.

**Comment by YiffyToys** [comment]
Thank you very much.
Only the first of these 4 menu items exist in our account.
Therefore we didn't know that feature existed. 
We'll contact Geschäftskundenportal to get the feature enabled and just close this issue as there clearly is a much better way to solve that issue.
