### ISSUE TITLE
Weird CSS errors

### ISSUE THREAD

**Issue by OvalMedia** [netresearch/dhl-shipping-m2#50]
I am maintaining 2 separate magentos (both 2.4.4). Both have the `dhl/shipping-m2` module (2.7.0) installed.

In one of those shops the admin part looks somewhat broken as if some css is missing:
![dhl-1](https://user-images.githubusercontent.com/1006378/188912190-3d0a9ffb-8375-49d7-88b3-b1c0d20d4469.png)

While in the other this looks fine:
![dhl-2](https://user-images.githubusercontent.com/1006378/188912288-68dce632-cea7-4b31-84b8-ebe10bcf080b.png)

How can I fix this?

In addition to that there is an issue with the display of dropdowns in BOTH shops:
![dhl-3](https://user-images.githubusercontent.com/1006378/188912598-6eb72dd2-933e-4388-8680-905a7c0adb23.png)

The dropdowns and text fields are all collapsed. This can be fixed by adding these classes to the form fields:
- `admin__control-text` for text inputs
- `admin__control-select` for selects

Maybe there are more of these classes. I haven't dug too deep but I have a feeling this is something new in 2.4.4. I had the same issue with another module after upgrading to 2.4.4.

**Comment by mam08ixo** [comment]
Please run `composer info -l netresearch*` and compare the result.

For us to be able to reproduce the issue, please add more detail about how you process CSS/LESS in your environments.

**Comment by mam08ixo** [comment]
Okay that does not look any special to me. Thing is, we have no such complaints from other merchants on our support channels and cannot replicate the issue in any of our environments. Neither does it occur consistently in yours.

We can certainly align our class attributes with the Magento core config field elements, but from there you are on your own I am afraid.

**Comment by OvalMedia** [comment]
Ok, thank you. The module itself seems to work fine. But the collapsed fields need a fix though.
