### ISSUE TITLE
CN22

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-shipping-m2#51]
Not sure if this us the Magento-Plugin (sinc eit transmits the shopping cart) or the DHL backend.

For a "Warensendung International" it prints a CN22 customs content declaration.
.... for shipments from Germany to Spain.
(but not for Germany to Portugal. )
Both are set up as EU countries in Stores->Config->General->General->Countries.

For shipments within the EU it should obviosly not do that.

**Comment by mam08ixo** [comment]
Your issues would really benefit from steps to reproduce. You did not mention the destination address but I assume you are sending to some territory outside of the EU’s customs and VAT regulations, and the CN22 being therefore correct.

**Comment by powli** [comment]
See also [this overview](https://www.dhl.de/content/dam/images/pdf/dhl-zollbestimmungen-eu-mitgliedsstaaten-022021.pdf) from DHL regarding special customs treatments and where the CN22 is required within European Union (content in German).

**Comment by YiffyToys** [comment]
Thanks. I was not aware that there are areas of Spain actually requiring a CN22 .
