### ISSUE TITLE
PSR Log ^1.1|^2|^3

### ISSUE THREAD

**Issue by in-session** [netresearch/dhl-shipping-m2#55]
Hello together, 

currently the dependencies seem to be still on PSR LOG 1.

deutschepost/sdk-api-addressfactory              2.0.1   requires  psr/log (^1.1.0)
deutschepost/sdk-api-autocomplete-authentication 1.1.0   requires  psr/log (^1.1.0)
deutschepost/sdk-api-oneclickforapp              1.1.0   requires  psr/log (^1.1)
deutschepost/sdk-api-oneclickforrefund           1.1.0   requires  psr/log (^1.1)
deutschepost/sdk-api-prodws                      1.1.2   requires  psr/log (^1.1)
dhl/sdk-api-bcs                                  1.3.0   requires  psr/log (^1.1)
dhl/sdk-api-bcs-returns                          2.1.2   requires  psr/log (^1.1.0)
dhl/sdk-api-parcel-management                    3.1.0   requires  psr/log (^1.1.0)
dhl/sdk-api-unified-location-finder              3.0.0   requires  psr/log (^1.1.0)
dhl/sdk-api-unified-tracking                     2.2.1   requires  psr/log (^1.1.0)

Expected
requires  psr/log (^1.1 || ^2.0 || ^3.0)

**Comment by mam08ixo** [comment]
Hi @in-session, the extension DHL Shipping for Magento 2 and its dependencies support `psr/log` v1 because this is the only version supported by the Magento 2 platform.

```sh
$ composer why-not psr/log 2

    laminas/laminas-di  3.12.0  requires  psr/log (^1.1.4 || ^3.0.0)

$ composer why-not psr/log 3

    opensearch-project/opensearch-php  2.0.0    requires   psr/log (^1|^2)  
    symfony/console                    v5.4.24  conflicts  psr/log (>=3)
```

We will publish compatible SDKs as soon as the platform opens up its `psr/log` dependencies for newer versions.

**Comment by in-session** [comment]
I think it will come in the next update:
https://github.com/opensearch-project/opensearch-php/blob/main/composer.json#L20C1-L20C1
https://github.com/symfony/console/blob/6.3/composer.json#L32

**Comment by Sebastian80** [comment]
Hi @in-session,

[Release 2.11.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/2.11.0) now has support for 
psr/log ^1.1 || ^2.0 || ^3.0.
