### ISSUE TITLE
Composer installation for Magento 2.4 fails

### ISSUE THREAD

**Issue by ibs83278** [netresearch/dhl-shipping-m2#6]
I tried to install the extension in a new clean environment of Magento 2.4.

 **composer require dhl/shipping-m2**

I get this output:

`Using version ^1.1 for dhl/shipping-m2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laminas/laminas-code (locked at 3.4.1) -> satisfiable by laminas/laminas-code[3.4.1].
    - dhl/shipping-m2 1.1.0 requires dhl/module-carrier-paket ~1.1.0 -> satisfiable by dhl/module-carrier-paket[1.1.0].
    - dhl/shipping-m2 1.1.0 requires dhl/module-carrier-paket ~1.1.0 -> satisfiable by dhl/module-carrier-paket[1.1.0].
    - dhl/module-carrier-paket 1.1.0 requires dhl/module-unified-tracking ^1.0.0 -> satisfiable by dhl/module-unified-tracking[1.0.0].
    - Conclusion: don't install dhl/module-unified-tracking 1.0.0
    - Installation request for dhl/shipping-m2 ^1.1 -> satisfiable by dhl/shipping-m2[1.1.0].

Installation failed, reverting ./composer.json to its original content.
`
Any suggestions would be nice, thanks a lot!

**Comment by powli** [comment]
Hi @ibs83278,

the explanation is simple: the module is not yet compatible with Magento 2.4. We are currently working on the compatibility and will provide it with the next release.

**Comment by powli** [comment]
See also https://github.com/netresearch/dhl-module-carrier-paket/issues/1#issuecomment-665493736

**Comment by ibs83278** [comment]
Thank you, so I´m looking forward to the new release.

**Comment by MarcusWolschon** [comment]
Why has this been closed when there is no new release
https://github.com/netresearch/dhl-shipping-m2/releases
?

**Comment by mam08ixo** [comment]
This issue was closed by the reporter because installing an incompatible module version must fail and will always fail.

**Comment by MarcusWolschon** [comment]
Not it will not always fail because a new version is suposed to be released that will BE compatible.
See above, 10 days ago!
"the module is not yet compatible with Magento 2.4. We are currently working on the compatibility and will provide it with the next release."

**Comment by ngolatka** [comment]
@MarcusWolschon Please read carefully:

> installing **an incompatible module version** must fail and will always fail

**Comment by MarcusWolschon** [comment]
Yes. The fix is to provide a compatible module version.  That is still in progress.

**Comment by ngolatka** [comment]
@MarcusWolschon If you are unhappy with this issue being closed, please discuss that with the one who closed it.

And also: #8
