### ISSUE TITLE
Class not found errors on Magento 2.4.6

### ISSUE THREAD

**Issue by yhling** [netresearch/dhl-shipping-m2#61]
Is this module compatible with Magento 2.4.6? After installing and running `bin/magento setup:di:compile` my Magento shop breaks whenever this DHL module is referenced.  
  
and in the logs I can see
`[2023-10-17T13:52:38.735794+00:00] main.CRITICAL: ReflectionException: Class "Netresearch\ShippingCore\Observer\JoinOrderItemAttributes" does not exist in /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php:34` 

`[2023-10-17T13:48:21.911644+00:00] main.CRITICAL: ReflectionException: Class "Netresearch\ConfigFields\Block\InfoBox" does not exist in /bitnami/magento/vendor/magento/framework/Code/Reader/ClassReader.php:34`

**Comment by mam08ixo** [comment]
Yes, the module is compatible with Magento 2.4.6

Please make sure to install all Composer dependencies. It looks like you are missing some required packages.
