### ISSUE TITLE
DHL module breaks 3rd party module after Update to newest version

### ISSUE THREAD

**Issue by tobiasolge** [netresearch/dhl-shipping-m2#62]
Hi,

after solving 3D Secure problem (https://github.com/netresearch/module-shipping-ui/issues/8) a new issue occured.

Compatibility with Magedelight SubscribeNow module is broken. After the update, the subscription module is unable to generate orders.
Order generation fails with the following error:

Error: Rolled back transaction has not been completed correctly.

Kind regards.
Tobias

**Comment by mam08ixo** [comment]
Can you provide any useful information that helps to narrow down the problem?
