### ISSUE TITLE
uninstallation of dhl/shipping-m2

### ISSUE THREAD

**Issue by tobiasolge** [netresearch/dhl-shipping-m2#65]
Hi,

ho to uninstall dhl/shipping-m2?

We disabled the following modules because of an incompatibility with another module.
magento module:disable Netresearch_ShippingCore Dhl_UnifiedTracking Netresearch_ConfigFields Dhl_ShippingCore Dhl_Paket Netresearch_AdminNotificationFeed Dhl_PaketReturns Netresearch_InteractiveBatchProcessing DeutschePost_Internetmarke Netresearch_ShippingUi PostDirekt_Autocomplete PostDirekt_Core

But there are still cronjobs running (postdirekt_addressfactory_autoprocess_job) which marks offline payment orders as paied, qhich they aren't and creates a shipment.

I tried to uninstall the modules from composer.json as described in the Readme files.
magento module:uninstall --remove-data PostDirekt_Autocomplete
magento module:uninstall --remove-data PostDirekt_Addressfactory
magento module:uninstall --remove-data DeutschePost_Internetmarke
magento module:uninstall --remove-data Dhl_Paket
magento module:uninstall --remove-data Dhl_PaketReturns

this does not work because of dependencies.

###
Command "remove" failed: <warning>dhl/module-carrier-paket-returns is not required in your composer.json and has not been removed</warning>

Removal failed, dhl/module-carrier-paket-returns is still present, it may be required by another package. See `composer why dhl/module-carrier-paket-returns`.

Please assist.

**Comment by ngolatka** [comment]
Hello @tobiasolge, did you try this command already?

`composer remove dhl/shipping-m2`

That should remove everything in a single step. You shouldn't have to remove all the modules manually.

**Comment by tobiasolge** [comment]
how come, that there still is a cronjob running?

**Comment by tobiasolge** [comment]
and why are orders, that are not paid marked as paid by the cron?

**Comment by powli** [comment]
@tobiasolge:

Which cron job is running? Also how do you determine the orders being  marked as paid?

**Comment by tobiasolge** [comment]
Hi,
job_code: postdirekt_addressfactory_autoprocess_job

**Comment by tobiasolge** [comment]
There seem to be some more problems.
We have the following errors:
Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.nrshipping_order_item' doesn't exist, query was: SELECT `main_table`.*, `extension_attribute_nrshipping_country_of_manufacture`.`country_of_manufacture` AS `extension_attribute_nrshipping_country_of_manufacture_country_of_manufacture`, `extension_attribute_nrshipping_export_description`.`export_description` AS `extension_attribute_nrshipping_export_description_export_description`, `extension_attribute_nrshipping_hs_code`.`hs_code` AS `extension_attribute_nrshipping_hs_code_hs_code` FROM `sales_order_item` AS `main_table` LEFT JOIN `nrshipping_order_item` AS `extension_attribute_nrshipping_country_of_manufacture` ON main_table.item_id = extension_attribute_nrshipping_country_of_manufacture.item_id LEFT JOIN `nrshipping_order_item` AS `extension_attribute_nrshipping_export_description` ON main_table.item_id = extension_attribute_nrshipping_export_description.item_id LEFT JOIN `nrshipping_order_item` AS `extension_attribute_nrshipping_hs_code` ON main_table.item_id = extension_attribute_nrshipping_hs_code.item_id WHERE ((`order_id` = ''))

**Comment by mam08ixo** [comment]
Hi @tobiasolge, I am not sure what you are asking for. How to remove a package from a project was already explained before:

`composer remove dhl/shipping-m2`

Obviously, there is still code in your project that

* executes cron jobs (none of our cron jobs marks orders as paid by the way, this is not a payment module) and
* attempts to access database tables that you have removed.

So the first step for you is to remove the module files completely from the project.

Second step is data cleanup. Given you receive that SQL error, I assume you cleaned up the database already. If not, restore a dump or compare the schema files with your database to detect any leftovers. Schema files:

* https://github.com/netresearch/module-shipping-core/blob/master/etc/db_schema.xml
* https://github.com/netresearch/module-admin-notification-feed/blob/master/etc/db_schema.xml
* https://github.com/netresearch/deutschepost-module-internetmarke/blob/master/etc/db_schema.xml
* https://github.com/netresearch/deutschepost-module-addressfactory-m2/blob/master/etc/db_schema.xml

**Comment by tobiasolge** [comment]
Hi, yes, but there is still a cronjob running....
job code: postdirekt_addressfactory_autoprocess_job

**Comment by mam08ixo** [comment]
Then I suggest you find out why it is still running. Something cache? Cron schedule still stored in configuration files/table?

**Comment by tobiasolge** [comment]
we do have nothing, that scheduled that cron.

**Comment by mam08ixo** [comment]
That's good news! When it is not scheduled, then it does not run.
