### ISSUE TITLE
DHL Module with MSI Enabled

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-shipping-m2#67]
Hello, is this module needed in order to use this with MSI enabled? https://github.com/netresearch/module-shipping-inventory

**Comment by Sebastian80** [comment]
Hello @simonmaass ,

if you want to use MSI, the mdoule is needed.

best regards,
Sebastian

**Comment by simonmaass** [comment]
Thank you for the info! Would you mind to elaborate what the module exactly does? Not really transparent if you read the readme... thank you so much!

**Comment by Sebastian80** [comment]
I was not that much involved during development of that module.
After reading some internal tickets, i think it does let you choose one of the sources from where to ship and decrements the product quantity. I am not sure how many people actually use it and if there are any problems.
As i currently do not have time to test this myself, i would advise to try it out on a Test/DEV System and see if it fit's your needs ?

Sorry that i can't be more of a help but i am currently pretty busy.

Best regards,
Sebastian

**Comment by simonmaass** [comment]
The module is no longer compatible with magento 2.4.7 - could you please either: update the module or state, that it is not needed with magento MSI... i am not really sure how to proceed...

**Comment by simonmaass** [comment]
https://github.com/netresearch/module-shipping-inventory/issues/3

**Comment by Sebastian80** [comment]
Hi @simonmaass,

we released a new [version](https://github.com/netresearch/module-shipping-inventory/releases/tag/1.2.0) which solves the compatibility issues and includes your PR.
