### ISSUE TITLE
Incompatibility with Magento 2.4.7

### ISSUE THREAD

**Issue by norgeindian** [netresearch/dhl-shipping-m2#68]
Today, Magento 2.4.7 has been published.
Unfortunately, the module is not compatible with this new version.
It would be awesome, if this could be fixed and a new release could be published.

**Comment by norgeindian** [comment]
@Sebastian80 , any update on this issue?

**Comment by Sebastian80** [comment]
Hi @norgeindian ,

we are currently working on it. Since we intent to drop PHP7.1 support und add support for PHP8.3 , we have a lot to change and need to change and test all involved SDKs and Modules, this is going to take some time. 
I can't give you an ETA, but be assured we are working on it. If everything goes smooth, we might finish it by the end of next week. 

regards,
Sebastian

**Comment by Sebastian80** [comment]
Hi guys,

just a short update. We are nearly done and have a installable and compatible version.
We need to do some internal testing and based on it's result, we might release a new version during this week.

**Comment by candreas-isp** [comment]
Unfortunately the new update to 2.11.0 doesn't solve the problem as it is not installable on Magento 2.4.7 with PHP 8.3:

  Problem 1
    - dhl/shipping-m2 2.8.0 requires dhl/module-carrier-paket-returns ~2.2.2 -> satisfiable by dhl/module-carrier-paket-returns[2.2.2].
    - dhl/shipping-m2[2.7.0, ..., 2.7.1] require dhl/module-carrier-paket-returns ~2.2.1 -> satisfiable by dhl/module-carrier-paket-returns[2.2.1, 2.2.2].
    - dhl/shipping-m2 2.6.0 requires dhl/module-carrier-paket-returns ~2.2.0 -> satisfiable by dhl/module-carrier-paket-returns[2.2.0, 2.2.1, 2.2.2].
    - dhl/shipping-m2 2.10.0 requires dhl/module-carrier-paket ~2.9.0 -> satisfiable by dhl/module-carrier-paket[2.9.0].
    - dhl/shipping-m2 2.9.0 requires dhl/module-carrier-paket ~2.8.0 -> satisfiable by dhl/module-carrier-paket[2.8.0].
    - dhl/shipping-m2 1.1.0 requires dhl/module-carrier-paket ~1.1.0 -> satisfiable by dhl/module-carrier-paket[1.1.0].
    - dhl/shipping-m2 1.2.0 requires dhl/module-carrier-paket-returns ~1.1.0 -> satisfiable by dhl/module-carrier-paket-returns[1.1.0, 1.1.1].
    - dhl/shipping-m2 1.0.0 requires dhl/module-carrier-paket ^1.0.0 -> satisfiable by dhl/module-carrier-paket[1.0.0, ..., 1.4.2].
    - dhl/shipping-m2 1.5.1 requires deutschepost/module-autocomplete-m2 ~1.1.1 -> satisfiable by deutschepost/module-autocomplete-m2[1.1.1].
    - dhl/shipping-m2[1.3.0, ..., 1.5.0] require deutschepost/module-autocomplete-m2 ~1.1.0 -> satisfiable by deutschepost/module-autocomplete-m2[1.1.0, 1.1.1].
    - dhl/shipping-m2 2.1.0 requires dhl/module-carrier-paket-returns ~2.0.2 -> satisfiable by dhl/module-carrier-paket-returns[2.0.2, 2.0.3].
    - dhl/shipping-m2 2.0.1 requires dhl/module-carrier-paket-returns ~2.0.1 -> satisfiable by dhl/module-carrier-paket-returns[2.0.1, 2.0.2, 2.0.3].
    - dhl/shipping-m2 2.0.0 requires dhl/module-carrier-paket-returns ~2.0.0 -> satisfiable by dhl/module-carrier-paket-returns[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - dhl/shipping-m2[2.4.0, ..., 2.5.0] require deutschepost/module-autocomplete-m2 ~1.2.1 -> satisfiable by deutschepost/module-autocomplete-m2[1.2.1].
    - dhl/shipping-m2[2.2.0, ..., 2.3.0] require deutschepost/module-autocomplete-m2 ~1.2.0 -> satisfiable by deutschepost/module-autocomplete-m2[1.2.0, 1.2.1].
    - dhl/module-carrier-paket-returns 2.2.2 requires dhl/sdk-api-bcs-returns ^2.1.2 -> satisfiable by dhl/sdk-api-bcs-returns[2.1.2].
    - dhl/module-carrier-paket-returns 2.2.1 requires dhl/sdk-api-bcs-returns ^2.1.1 -> satisfiable by dhl/sdk-api-bcs-returns[2.1.1, 2.1.2].
    - dhl/module-carrier-paket-returns 2.2.0 requires dhl/sdk-api-bcs-returns ^2.1.0 -> satisfiable by dhl/sdk-api-bcs-returns[2.1.0, 2.1.1, 2.1.2].
    - dhl/module-carrier-paket 2.9.0 requires dhl/sdk-api-bcs ^2.2.0 -> satisfiable by dhl/sdk-api-bcs[2.2.0].
    - dhl/module-carrier-paket 2.8.0 requires dhl/sdk-api-bcs ^2.0.0 -> satisfiable by dhl/sdk-api-bcs[2.0.0, 2.1.0, 2.2.0].
    - dhl/module-carrier-paket[1.0.0, ..., 1.1.0] require php ~7.0.6 || ~7.1.3 || ~7.2.0 || ~7.3.0 -> your php version (8.3.7) does not satisfy that requirement.
    - dhl/module-carrier-paket[1.2.0, ..., 1.4.2] require php ^7.1.3 -> your php version (8.3.7) does not satisfy that requirement.
    - deutschepost/module-autocomplete-m2[1.1.0, ..., 1.2.1] require php ^7.1.3 -> your php version (8.3.7) does not satisfy that requirement.
    - dhl/module-carrier-paket-returns[1.1.0, ..., 1.1.1, 2.0.0, ..., 2.0.3] require php ^7.1.3 -> your php version (8.3.7) does not satisfy that requirement.
    - dhl/sdk-api-bcs-returns[2.1.0, ..., 2.1.2] require psr/http-message ^1.0.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dhl/sdk-api-bcs[2.0.0, ..., 2.2.0] require psr/http-message ^1.0.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - dhl/shipping-m2 2.11.0 requires deutschepost/module-addressfactory-m2 ~1.5.0 -> found deutschepost/module-addressfactory-m2[dev-master, 1.0.0, ..., 1.4.2] but it does not match the constraint.
    - Root composer.json requires dhl/shipping-m2 * -> satisfiable by dhl/shipping-m2[1.0.0, ..., 1.5.1, 2.0.0, ..., 2.11.0].

Do you have any hints how this will work with the new release?

Thank you,
Christoph

**Comment by Sebastian80** [comment]
Hi guys, 

as you might noticed, we released a new version 2.11.0 which is compatible with Magento 2.4.6 and 2.4.7.

**Comment by YiffyToys** [comment]
Looks like there is still an inconsistency.

```
magento/product-community-edition 2.4.7 requires psr/log ^2 || ^3 -> satisfiable by psr/log[2.0.0, 3.0.0].

deutschepost/sdk-api-oneclickforapp              1.1.0   requires  psr/log (^1.1)
deutschepost/sdk-api-oneclickforrefund           1.1.0   requires  psr/log (^1.1)
deutschepost/sdk-api-prodws                      1.1.2   requires  psr/log (^1.1)
```

**Comment by Sebastian80** [comment]
Hi @YiffyToys ,

looking at the provided composer output you somehow have an requirement for `dhl/shipping-m2 2.10.0` ?
The new version of `dhl/shipping-m2:2.11.0` should have compatibility with Magento 2.4.7 and Magento 2.4.6.
We tested this, so did our CI and so did Magento during the Marketplace upload, which was passed.

**Comment by simonmaass** [comment]
This is not compatible with Magento MSI: https://github.com/netresearch/module-shipping-inventory/issues/3

**Comment by Sebastian80** [comment]
Hi @simonmaass,

we released a new [version](https://github.com/netresearch/module-shipping-inventory/releases/tag/1.2.0) which now is compatible with Magento 2.4.7.
