### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by simonmaass** [netresearch/dhl-shipping-m2#69]
Since 2.11 this is no longer valid:

Generally, Post & DHL Shipping is compatible with PHP 7.2.0 and later, and Magento 2.3.5 and later.

**Comment by Sebastian80** [comment]
Hi @simonmaass,

thanks for the info, somehow we missed it.

The Readme is now updated. 

Best regards,
Sebastian

**Comment by simonmaass** [comment]
hey @Sebastian80 , you wrote "2.6.0" - you probably mean "2.4.x" ;)

**Comment by Sebastian80** [comment]
Hi @simonmaass ,

that's right. Thank you.

**Comment by Sebastian80** [comment]
should be fixed
