### ISSUE TITLE
Module not available for Magento 2.4.0?

### ISSUE THREAD

**Issue by NeilofSteel** [netresearch/dhl-shipping-m2#7]
Getting this error if I try to run "composer require dhl/shipping-m2" (PHP Version: 7.3.20)

![Screenshot](https://user-images.githubusercontent.com/58559388/90114236-bd3a6900-dd52-11ea-98db-aeea4429cde8.PNG)

**Comment by NeilofSteel** [comment]
#6

**Comment by ngolatka** [comment]
Please see #8
