### ISSUE TITLE
Can't install v2.11.0 with php lower than 8.2

### ISSUE THREAD

**Issue by Detzler** [netresearch/dhl-shipping-m2#70]
Hi,

since dhl/shipping-m2 in v2.11.0 has updated the composer dependency to deutschepost/module-autocomplete-m2 v1.5.0, it's not possible to install dhl/shipping-m2:2.11.0 when using php below 8.2

Composer install result:

> Problem 1
    - deutschepost/module-autocomplete-m2 1.5.0 requires php ^8.2.0 -> your php version (8.1.29) does not satisfy that requirement.
    - dhl/shipping-m2 2.11.0 requires deutschepost/module-autocomplete-m2 ~1.5.0 -> satisfiable by deutschepost/module-autocomplete-m2[1.5.0].
    - Root composer.json requires dhl/shipping-m2 2.11.0 -> satisfiable by dhl/shipping-m2[2.11.0].

Please downgrade the dep back to 1.4 or fix deutschepost/module-autocomplete-m2

Magento: 2.4.6-p6
PHP: 8.1.29

**Comment by Sebastian80** [comment]
Hi @Detzler ,

we missed updating the readme for release 2.11.0.
We support Magento 2.4.6-x upwards but only for PHP 8.2+.
Is there anything preventing you to update to PHP 8.2 ?

Best regards,
Sebastian

**Comment by Detzler** [comment]
Hello @Sebastian80 

> Is there anything preventing you to update to PHP 8.2 ?

Actually a lot of internal circumstances and decisions.

> We support Magento 2.4.6-x

Not true. deutschepost/module-autocomplete-m2 goes even further. It dropped support for Magento v2.4.6

![image](https://github.com/netresearch/dhl-shipping-m2/assets/1556434/14689e21-17f4-4ff0-8f8d-5cb5753a5e2e)

Since you advertise compatibility for Magento >= v2.4.6 then please do it according to it's minimal system requirements:

![image](https://github.com/netresearch/dhl-shipping-m2/assets/1556434/10b60d90-ad89-43ea-b1f6-907e812a1a9b)

Honestly, I don't understand vendors dictating their clients to use a specific php version. Just stick to the minimal plattform requirements and everybody is happy and especially it is easy on the client's dev budget.

**Comment by Sebastian80** [comment]
Hi @Detzler ,

i fixed the wrong release description for module-autocomplete.
As stated above, we support Magento 2.4.6+ with PHP 8.2 + and we did this on purpose after internal discussion.
There are alot of SDKs and Modules involved with code style and analyse checks, unit tests docker images and CI Testing, and so one. I honestly do not see us opening up the php requirement to have all involved stuff be working on php8.1 again, sorry. 

If you can not update to PHP8.2, you would need to stick to Version 2.10.0 .

best regards,
Sebastian

**Comment by ngolatka** [comment]
It is also worth mentioning that PHP 8.1 is in the [security fixes only-phase](https://www.php.net/supported-versions), which makes upgrading to PHP 8.2 a good idea, regardless of DHL Shipping/Autocomplete.

And even for PHP 8.2 the end is not too far away...

**Comment by Detzler** [comment]
The security breaches are coming through extensions and magento itself, but less through php. Even if PHP 8.1 is completely EOL, let it be the problem of the merchant. I assume a lot of merchants use your extension. You literaly locked the gates for those who want to update your extension due to security holes are other business critical changes in the dhl module. Did you really used so much v8.2 specific features in the source code that it's impossible now to keep compatibility for v8.1? Can't imagine that replicating the CI process for v8.1 have that much impact on the budget.

**Comment by powli** [comment]
Version 2.11.0 was (and still is) intended as a compatibility release for Magento 2.4.7. The changeset for the release is following that.

The only reason, why we have opened up the compatibility to 2.4.6 (with PHP 8.2) at all is because Magento Marketplace automatic testing runs on that version and without it, we would not have been able to provide a Marketplace release.

There is no one forcing you to upgrade to this release and no explicit reason to do so. You can like that or not, but we are not obligated to act on your opinion. The source code of the extensions and involved SDKs is all open source, if you see necessary changes, feel free to make the adjustments you need.

Further releases of this extension and the accompanying packages will target 2.4.7+ with the respective minimum requirements as long as Magentos automatic testing allows that.
