### ISSUE TITLE
[Feature Request] Magento 2.4 support

### ISSUE THREAD

**Issue by MartinSchillinger** [netresearch/dhl-shipping-m2#8]
Is there a plan or timeline for implementing Magento 2.4 support?

**Comment by ngolatka** [comment]
@MartinSchillinger Yes, this is already in work, but the task isn't trivial.

There is no exact, bullet-proof timeline, but we aim for end of September 2020.

**Comment by DavidLambauer** [comment]
Hi there,

are there any updates regarding the 2.4 compatibilities? Is there something we can help with?

**Comment by ngolatka** [comment]
Hello @DavidLambauer , as I wrote above, we aim for end of September 2020. Because of the complexity, things will most likely not go much faster than that, sorry.

**Comment by simonmaass** [comment]
@ngolatka haha - not quite sure what it means... was trying to say that am "watching" this issue and very much looking forward to the 2.4 support :)

**Comment by ngolatka** [comment]
G'day y'all, the [new version 1.2.0](https://github.com/netresearch/dhl-shipping-m2/releases/tag/1.2.0) has been released. It is compatible with Magento 2.4.

Support for Magento 2.2 and below has been removed.

**Please note:** There's a [known bug in Magento 2.4](https://support.magento.com/hc/en-us/articles/360046750171-Shipping-labels-creation-known-issue-in-Magento-2-4-0) which results in the checkbox "_Create shipping labels_" not being displayed. The solution is to install [this patch](https://support.magento.com/hc/en-us/article_attachments/360063419631/MC-35514-2.4.0-CE-composer-2.patch) (applies ONLY to Magento 2.4).

If you don't see the checkbox "_Create shipping labels_" and you are NOT using M 2.4, have a look at [this FAQ article](https://dhl.support.netresearch.de/support/solutions/articles/12000027151).

**Comment by MartinSchillinger** [comment]
Thank you :-)

**Comment by YiffyToys** [comment]
Looks like not all dependencies exist in a stable release yet.

 Problem 1
    - dhl/module-carrier-paket 1.2.0 requires dhl/sdk-api-parcel-management ^2.0.0 -> satisfiable by dhl/sdk-api-parcel-management[2.0.0] but these conflict with your requirements or minimum-stability.

**Comment by ngolatka** [comment]
Hello @YiffyToys, during my test, the installation worked perfectly fine. Other people have also confirmed that it works.

Note this part:
> these conflict with your requirements or minimum-stability.

Have a look at your composer.lock about that, specifically the version of said SDK. My guess is the version is fixed to "1.0.0".

Also, this article might be relevant: https://dhl.support.netresearch.de/support/solutions/articles/12000074592

**Comment by YiffyToys** [comment]
We traced it to a dependency of a dependency of a dependency.
The Composer error messages where a bit misleading.
